app/models/comment.rb
app/models/favorite.rb
app/models/item_image.rb
app/models/purchase.rb
app/models/residence.rb
db/migrate/20200213121558_create_residences.rb
db/migrate/20200214012659_create_comments.rb
db/migrate/20200214013409_create_purchases.rb
db/migrate/20200214013847_create_item_images.rb
db/migrate/20200214014114_create_favorites.rb
db/schema.rb
test/factories/comments.rb
test/factories/favorites.rb
test/factories/item_images.rb
test/factories/purchases.rb
test/factories/residences.rb
test/models/comment_test.rb
test/models/favorite_test.rb
test/models/item_image_test.rb
test/models/purchase_test.rb
test/models/residence_test.rb

#What
gemの必要のないデータベースのモデルとマイグレーションファイル作成。
#Why
必要なデータベースを揃えるため。

[WIP]gemが不要なデータベースモデル・マイグレーション作成

---

app/assets/stylesheets/_show-item.scss
app/assets/stylesheets/application.scss
app/views/items/show.html.haml

商品の詳細ページのビューを作成
商品の詳細ページを作成することで、
商品を購入してもらう為に、ユーザーにどのような商品かを伝える必要がある為。

商品詳細ページ　マークアップ

---

app/models/comment.rb
app/models/item.rb
app/models/item_image.rb
app/models/purchase.rb
app/models/residence.rb
app/models/user.rb

モデルのバリデーションを、
null: falseと記述している箇所を
presence: trueに変更。
null: falseだと””空文字をパスしてしまう為
presence: trueに変更

モデル、バリデーション変更

---

app/assets/stylesheets/_show-item.scss
app/assets/stylesheets/application.scss
app/views/items/show.html.haml

Reverts Shin-tech25/freemarket_sample_68k#14

Revert "Revert "商品詳細ページ　マークアップ""

---

app/assets/stylesheets/_item_index.scss
app/assets/stylesheets/_sell_btn.scss
app/assets/stylesheets/application.scss

#What 
トップページのビュー崩れの修正
itemとsell-btnに当たっていたscssを修正
#Why
ビューが崩れていたため手直しする必要があった

[WIP]  トップページのビュー崩れ修正

---

app/assets/stylesheets/_item_index.scss
app/assets/stylesheets/_items_index.scss
app/views/items/_item.html.haml

#What
トップページのビューが崩れている箇所を修正
#Why
変更ファイルが消えてしまっていた箇所(コンフリクトの際に消えてしまった可能性がある)があったので、再度編集して追加する必要があった

[WIP] トップページのビュー崩れ修正

---

app/assets/javascripts/categories.coffee
app/assets/stylesheets/categories.scss
app/controllers/categories_controller.rb
app/controllers/items_controller.rb
app/controllers/residences_controller.rb
app/controllers/users_controller.rb
app/helpers/categories_helper.rb
app/views/devise/sessions/new.html.haml
app/views/purchases/show.html.haml
app/views/residences/show.html.haml
app/views/shared/_footer.html.haml
app/views/shared/_header.html.haml
app/views/shared/_sellbtn.html.haml
app/views/shared/_sub_header.html.haml
app/views/shared/popup/_popup_mypage.html.haml
app/views/users/show.html.haml
config/routes.rb
spec/controllers/categories_controller_spec.rb
spec/helpers/categories_helper_spec.rb

#What
=link_to リンク宛て作成
暫定版、今後リンクは増えます。
#Why
リンクが必要。

[WIP]リンク宛て作成

---

app/assets/javascripts/sign-up.js
app/views/devise/registrations/new.html.haml

Reverts Shin-tech25/freemarket_sample_68k#34

Revert "ユーザー新規登録ページのエラーハンドリング"

---

app/assets/stylesheets/_purchase.scss
app/controllers/purchases_controller.rb
app/controllers/residences_controller.rb
app/views/purchases/get_purchase_modify.html.haml
app/views/purchases/index.html.haml
app/views/residences/index.html.haml
app/views/shared/_sub_footer.html.haml
app/views/shared/_sub_header.html.haml
config/routes.rb

#What
配送先情報変更
マイページから遷移するフォーム及び、購入ページから遷移するフォーム
ルーティング、コントローラー、ビュー

Revert "Revert "[WIP]商品購入機能（サーバーサイド）配送先情報変更""

---

db/seeds.rb

[WIP]Category

---

app/models/item.rb
spec/factories/item_images.rb
spec/factories/items.rb
spec/factories/purchases.rb
spec/models/item_image_spec.rb
spec/models/item_spec.rb
spec/models/purchase_spec.rb
test/factories/item_images.rb
test/factories/purchases.rb

#What
item, item-image, purchaseモデルの単体テストコードを記述
現段階で記述できるバリテーションに関するテストコードを記述
#Why
動作確認をするため

[WIP]  モデルの単体テスト

---

app/controllers/items_controller.rb
app/controllers/purchases_controller.rb
app/controllers/residences_controller.rb
app/controllers/users_controller.rb
app/views/devise/registrations/new.html.haml
app/views/items/show.html.haml
app/views/purchases/index.html.haml
app/views/shared/popup/_popup_mypage.html.haml
app/views/users/show.html.haml
config/routes.rb
db/migrate/20200225111610_add_residence_ref_to_users.rb
db/schema.rb

[WIP]purchase関連の修正

---

app/assets/javascripts/item_error.js
app/assets/stylesheets/_items-new.scss
app/controllers/items_controller.rb
app/views/devise/registrations/new.html.haml
app/views/items/new.html.haml

#What
商品出品画面において、入力必須の項目に記述・選択がない場合に、エラー文を表示。（商品出品機能カードの一環です）
#Why
ユーザーに未入力箇所を明示するため。

[WIP]商品出品画面のエラーハンドリング

---

app/assets/javascripts/card.coffee
app/assets/javascripts/item.js
app/assets/javascripts/items.coffee
app/assets/javascripts/post_images.js
app/assets/javascripts/residences.coffee
app/assets/javascripts/users.coffee
app/assets/stylesheets/_items-new.scss
app/controllers/purchases_controller.rb
app/views/items/new.html.haml

Reverts Shin-tech25/freemarket_sample_68k#54

Revert "Revert "[WIP]画像投稿プレビュー機能""

---

app/assets/javascripts/card.coffee
app/assets/javascripts/item.js
app/assets/javascripts/items.coffee
app/assets/javascripts/post_images.js
app/assets/javascripts/residences.coffee
app/assets/javascripts/users.coffee
app/assets/stylesheets/_items-new.scss
app/controllers/purchases_controller.rb
app/views/items/new.html.haml

Reverts Shin-tech25/freemarket_sample_68k#57

Revert "Revert "Revert "Revert "[WIP]画像投稿プレビュー機能""""

---

app/assets/javascripts/PayOff.js
app/assets/javascripts/card.coffee
app/assets/javascripts/categories.coffee
app/assets/javascripts/items.coffee
app/assets/javascripts/residences.coffee
app/assets/javascripts/users.coffee

販売手数料と販売利益計算。
商品出品画面において値段を設定すると、自動的に販売手数料と利益を算出してくれる。
出品者に商品を出品する前に利益と手数料を把握してもらうため。
[![Screenshot from Gyazo](https://gyazo.com/f049367c9b6e1be266f09a4f3543800a/raw)](https://gyazo.com/f049367c9b6e1be266f09a4f3543800a)

販売手数料と利益の計算

---

app/assets/javascripts/item_edit_error.js
app/assets/stylesheets/users/_new_registration.scss
app/views/items/edit.html.haml

商品編集のエラーハンドリング
バリデーション にかかった時にエラーを編集画面に表示するため。

商品編集　エラーハンドリング

---

app/controllers/card_controller.rb
app/controllers/items_controller.rb
app/controllers/purchases_controller.rb
app/controllers/residences_controller.rb
app/controllers/users_controller.rb

ログインしてない状態で商品一覧と商品詳細ページ以外へ遷移しようとすると、ログインページへいく
不正なユーザーが商品の情報を編集できないようにするため。

ログインページへリダイレクト

---

Gemfile
Gemfile.lock
app/models/item.rb
spec/factories/categorys.rb
spec/factories/items.rb
spec/models/item_spec.rb

itemのテストコード作成
正しいプログラミングができているか確認できるようにするため

items モデルのテストコード

---

spec/factories/categorys.rb
spec/factories/item_images.rb
spec/factories/items.rb

#Why
Factorybotのimageが読み取られていなかったため、コードを修正

item_imageのテストコードの修正
